//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int No { get; set; }
        public Nullable<int> userID { get; set; }
        public string itemName { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> categoryID { get; set; }
    }
}
